language: python

python:
 - "3.85"

install:
 - pip install coverage coveralls pandas influxdb matplotlib numpy==1.16.5 python-binance tables==3.5.2

script: 
 - coverage run --source=cryptoalgotrading setup.py test

after_success:
 - coveralls
